version: '3.4'


name: hospitality-hub

services:
  hospitality-hub.api:
    container_name: hospitality-hub-api
    image: ${DOCKER_REGISTRY-}hospitality-hub-api
    build:
      context: .
      dockerfile: src/HospitalityHub.API/Dockerfile
    depends_on:
    - hospitality-hub.db

  hospitality-hub.db:
    container_name: hospitality-hub-db
    image: postgres:16.2-alpine
    
  
  hospitality-hub-rabbitmq:
    container_name: hospitality-hub-rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
      
  hospitality-hub.pgadmin:
    container_name: hospitality-hub-pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/root/.pgadmin
    
volumes:
    rabbitmq_data:
    rabbitmq_logs:
    pgadmin_data:

